services:
  tm_app:
    image: ghcr.io/victorvangeli/python-project-52:latest
    container_name: tm_app
    command: >
      sh -c "make migrate &&
             make render-start"
    ports:
      - "8010:8000"
    volumes:
      - tm_app_data:/app
    env_file:
      - ./.env
    depends_on:
      - tm_db

  tm_db:
    container_name: postgres
    image: postgres:16.8-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgres
    ports:
      - "5432:5432"

#  caddy:
#    image: caddy:latest
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#      - ./caddy/caddy_data:/data
#      - ./caddy/caddy_config:/config

volumes:
  tm_app_data:

networks:
  default:
    name: caddy_net
    external: true
