services:
  tm_app:
    image: gitlab-dr.itsupport.host/whgaleon1/hexlet-last:latest
    container_name: tm_app
    command: >
      sh -c "make migrate &&
             uv run gunicorn -b 0.0.0.0:8000 task_manager.wsgi"
    volumes:
      - tm_app_data:/app
    env_file:
      - ./.env
    depends_on:
      - tm_db

  tm_db:
    container_name: postgres
    image: postgres:16.8-alpine
    restart: always
    environment:
      - POSTGRES_USER=tm_pan
      - POSTGRES_PASSWORD=tm_pass
      - POSTGRES_DB=tm_db
    volumes:
      - /var/lib/postgres

#  caddy:
#    image: caddy:latest
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#      - ./caddy/caddy_data:/data
#      - ./caddy/caddy_config:/config

volumes:
  tm_app_data:

networks:
  default:
    name: caddy_net
    external: true
